// <auto-generated />
using System;
using Commissions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Commissions.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commissions.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("commission");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019349e5-8e2b-7000-a000-000000000001"),
                            Commission = 10m,
                            IsActive = true,
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("019349e5-8e2b-7000-a000-000000000002"),
                            Commission = 15m,
                            IsActive = true,
                            Name = "Estados_Unidos"
                        },
                        new
                        {
                            Id = new Guid("019349e5-8e2b-7000-a000-000000000003"),
                            Commission = 12m,
                            IsActive = true,
                            Name = "Reino_Unido"
                        });
                });

            modelBuilder.Entity("Commissions.Domain.Entities.Sales", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<Guid>("Id_Country")
                        .HasColumnType("uuid")
                        .HasColumnName("id_country");

                    b.Property<decimal>("Total_Commission")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_commission");

                    b.Property<decimal>("Total_Sales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_sales");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("Id_Country")
                        .HasDatabaseName("ix_sales_id_country");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("Commissions.Domain.Entities.Sales", b =>
                {
                    b.HasOne("Commissions.Domain.Entities.Country", "Country")
                        .WithMany("Sales")
                        .HasForeignKey("Id_Country")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_countries_id_country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Commissions.Domain.Entities.Country", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
